### ISSUE TITLE
DTLS-fingerprint=SHA-256 with Chrome WebRTC fails

### ISSUE THREAD

**Issue by juha-h** [sipwise/rtpengine#1095]
I made more testing with and without DTLS-fingerprint-SHA-256 in the offer.  Call works fine without the key, but with key audio is only one way and debug complains about no crypto suite negotiation.

I placed the two debug outputs here:

https://tutpro.com/tmp/chrome-sha1.debug
https://tutpro.com/tmp/chrome-sha256.debug

Chrome console does not show any errors or warnings.

Any ideas why crypto suite was not negotiated when DTLS-fingerprint=SHA-256 was present?

**Comment by rfuchs** [comment]
I'm guessing the `DTLS fingerprint changed, restarting DTLS` gets in the way. The DTLS restart shouldn't happen, but it should also still work, so that needs 2 fixes. First, try with 37ad473 and see if that fixes it for you.

**Comment by rfuchs** [comment]
Sorry I left out the actual fix. Correct commit is 0f6313be

**Comment by juha-h** [comment]
I applied the two commits to master, built Debian packages and installed daemon and utils packages.  Then I made the test again, but unfortunately audio was still one way.

I copied the new debug log over

https://tutpro.com/tmp/chrome-sha256.debug

**Comment by juha-h** [comment]
Here is working debug when using Firefox:

https://box.tutpro.com/tmp/firefox-sha256.debug

**Comment by rfuchs** [comment]
Ok, the difference is that Firefox waits with starting DTLS until after the answer comes in. I've added a few fixes in 4a7f899 (branch `rfuchs/1095`), that should fix this.

**Comment by juha-h** [comment]
Unfortunately the issue still persists.  The debug is updated:

https://tutpro.com/tmp/chrome-sha256.debug

**Comment by rfuchs** [comment]
That's an improvement, DTLS is actually able to finish now, but gets reset at the answer, probably due to a typo. See 377f848

**Comment by juha-h** [comment]
With latest 1095 branch, media works both ways also with Chrome! Thanks for the effort.
