### ISSUE TITLE
kamailio+rtpengine: There is audio in one direction and no audio in the other direction

### ISSUE THREAD

**Issue by Sunldon** [sipwise/rtpengine#659]
My kamailio version: kamailio 5.1.6 (x86_64/linux) e178b8

the kamailio + rtpengine work on the 10.10.200.77, and I use rtpengine as :./rtpengine -n 127.0.0.1:7722 --interface=pub/10.10.200.77 --interface=priv/192.168.200.77

I have two softphone, one is in 10.10.18.203, two is 192.168.18.45. They have registered successfully in kamailio.

when I start a call from 10.10.18.203(2001@10.10.18.203:63492) to 192.168.18.45(1001@192.168.18.45:5060), it can be acceptable. but the problem is that only one direction has audio, the other direction doesn't have audio.
(2001@10.10.18.203:63492) <-->kamailio+rtpengine<-->(1001@192.168.18.45:5060)

the log is that:

Nov 19 16:56:00 localhost /usr/local/sbin/kamailio[45177]: {1 1 INVITE OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.} INFO: <script>: 11111111111111111111111111111111111111
Nov 19 16:56:00 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: Received command 'offer' from 127.0.0.1:35763
Nov 19 16:56:00 localhost rtpengine[45092]: NOTICE: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: Creating new call
Nov 19 16:56:00 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: Replying to 'offer' from 127.0.0.1:35763 (elapsed time 0.000240 sec)
Nov 19 16:56:00 localhost /usr/local/sbin/kamailio[45198]: {2 1 INVITE OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.} INFO: <script>: 222222222222222222222222222222222222222
Nov 19 16:56:09 localhost /usr/local/sbin/kamailio[45187]: {2 1 INVITE OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.} INFO: <script>: 11111111111111111111111111111111111111
Nov 19 16:56:09 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: Received command 'answer' from 127.0.0.1:45910
Nov 19 16:56:09 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: Enabling transcoding engine
Nov 19 16:56:09 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: Replying to 'answer' from 127.0.0.1:45910 (elapsed time 0.000228 sec)
Nov 19 16:56:09 localhost /usr/local/sbin/kamailio[45187]: {2 1 INVITE OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.} NOTICE: acc [acc.c:281]: acc_log_request(): ACC: transaction answered: timestamp=1542617769;method=INVITE;from_tag=124c1f5f;to_tag=ee68ec09;call_id=OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.;code=200;reason=OK;src_user=2001;src_domain=10.10.200.77;src_ip=10.10.18.203;dst_ouser=1001;dst_user=1001;dst_domain=192.168.18.45
Nov 19 16:56:09 localhost /usr/local/sbin/kamailio[45178]: {1 1 ACK OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.} INFO: <script>: setflag flb_natb
Nov 19 16:56:09 localhost /usr/local/sbin/kamailio[45178]: {1 1 ACK OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.} INFO: <script>: 222222222222222222222222222222222222222
Nov 19 16:56:13 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE. port 30020]: Confirmed peer address as 192.168.18.45:5062
Nov 19 16:56:15 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE. port 30021]: Confirmed peer address as 192.168.18.45:5063
Nov 19 16:56:17 localhost /usr/local/sbin/kamailio[45179]: {1 2 BYE OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.} INFO: <script>: setflag flb_natb
Nov 19 16:56:17 localhost /usr/local/sbin/kamailio[45179]: {1 2 BYE OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.} INFO: <script>: 222222222222222222222222222222222222222
Nov 19 16:56:17 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: Received command 'delete' from 127.0.0.1:35540
Nov 19 16:56:17 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: Scheduling deletion of call branch '124c1f5f' (via-branch '') in 30 seconds
Nov 19 16:56:17 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: Replying to 'delete' from 127.0.0.1:35540 (elapsed time 0.000044 sec)
Nov 19 16:56:17 localhost /usr/local/sbin/kamailio[45191]: {2 2 BYE OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.} NOTICE: acc [acc.c:281]: acc_log_request(): ACC: transaction answered: **timestamp=1542617777;method=BYE;from_tag=124c1f5f;to_tag=ee68ec09;call_id=OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.;code=200;reason=OK;src_user=2001;src_domain=10.10.200.77;src_ip=10.10.18.203;dst_ouser=1001;dst_user=1001;dst_domain=192.168.18.45**

Nov 19 16:56:48 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: Call branch '124c1f5f' (via-branch '') deleted, no more branches remaining
Nov 19 16:56:48 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: Final packet stats:
Nov 19 16:56:48 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: --- Tag '124c1f5f', created 0:48 ago for branch '', in dialogue with 'ee68ec09'
Nov 19 16:56:48 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: ------ Media #1 (audio over RTP/AVP) using unknown codec
Nov 19 16:56:48 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: --------- **Port  192.168.200.77:30032 <>    10.10.18.203:41298,** SSRC 0, 0 p, 0 b, 0 e, 48 ts
Nov 19 16:56:48 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: --------- **Port  192.168.200.77:30033 <>    10.10.18.203:41299 (RTCP),** SSRC 0, 0 p, 0 b, 0 e, 48 ts
Nov 19 16:56:48 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: --- Tag 'ee68ec09', created 0:48 ago for branch '', in dialogue with '124c1f5f'
Nov 19 16:56:48 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: ------ Media #1 (audio over RTP/AVP) using PCMU/8000
Nov 19 16:56:48 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: --------- **Port  192.168.200.77:30020 <>   192.168.18.45:5062 ,** SSRC 46b1c234, 385 p, 66220 b, 0 e, 31 ts
Nov 19 16:56:48 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: --------- **Port  192.168.200.77:30021 <>   192.168.18.45:5063  (RTCP),** SSRC 46b1c234, 4 p, 596 b, 0 e, 31 ts

I think the problem is ::
Nov 19 16:56:48 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: ------ Media #1 (audio over RTP/AVP) using unknown codec
Nov 19 16:56:48 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: --------- Port  192.168.200.77:30032 <>    10.10.18.203:41298, SSRC 0, 0 p, 0 b, 0 e, 48 ts
Nov 19 16:56:48 localhost rtpengine[45092]: INFO: [OGFkZDBjNTU2YzRkZmEwYTk2ZTY2YzgyOWM5ZGY4OWE.]: --------- Port  192.168.200.77:30033 <>    10.10.18.203:41299 (RTCP), SSRC 0, 0 p, 0 b, 0 e, 48 ts

it should be "Port  10.10..200.77:30032 <>    10.10.18.203:41298, SSRC 0, 0 p, 0 b, 0 e, 48 ts", not "Port  192.168.200.77:30032 <>    10.10.18.203:41298, SSRC 0, 0 p, 0 b, 0 e, 48 ts".

And my part of kamailio.cfg is as below:
route[NATMANAGE] {

      #!ifdef WITH_NAT
        if (is_request()) {
                if(has_totag()) {
                        if(check_route_param("nat=yes")) {
                                xinfo("setflag flb_natb");
                                setbflag(FLB_NATB);
                        }
                }
        }

        if (!(isflagset(FLT_NATS) || isbflagset(FLB_NATB))) return;

        if(nat_uac_test("8")) {
                xinfo("11111111111111111111111111111111111111");
                rtpengine_manage("codec-strip-all codec-transcode-PCMA codec-transcode-PCMU codec-transcode-G729");
        } else {
                xinfo("222222222222222222222222222222222222222");
                rtpengine_manage("codec-strip-all codec-transcode-PCMA codec-transcode-PCMU codec-transcode-G729 direction-priv direction-pub");
        }

        if (is_request()) {
                if (!has_totag()) {
                        if(t_is_branch_route()) {
                                add_rr_param(";nat=yes");
                        }
                }
        }

        if (is_reply()) {
                if(isbflagset(FLB_NATB)) {
                        if(is_first_hop())
                                set_contact_alias();
                }
        }
      #!endif

        return;
   }

I don't know how to correctly rewrite the SDP body.  What's wrong with my configure file?

**Comment by rfuchs** [comment]
One side (local port 30032) is not receiving any media packets. You would get a more helpful log if you run rtpengine with log level 7. Some suggestions: If your clients support ICE, use one of the `ICE=` flags, usually either `ICE=force` or `ICE=remove`. Also you seem to be using transcoding flags in both `offer` and `answer`. Using them in an `answer` probably doesn't produce meaningful results, so you should use them in the `offer` only.

**Comment by Sunldon** [comment]
I change rtpengine log level to 7,  and I add "#!define WITH_DEBUG" to kamailio.cfg.  I also use ICE=force in the kamailio.cfg. 
There is the change in my kamailio.cfg file: 
rtpengine_manage("codec-strip-all codec-transcode-PCMA codec-transcode-PCMU codec-transcode-G729 direction=priv direction=pub ICE=remove");

This is my log:
[kamai_rtpengine_v1.log](https://github.com/sipwise/rtpengine/files/2598466/kamai_rtpengine_v1.log)

My enviroment is : a softphone in 10.10.18.203 machine A, a softphone in 192.168.18.45 machine B, and kamailio+rtpengine work on the machine C that have IP 10.10.200.77, 192.168.200.77. 

phone(10.10.18.203)<-->(10.10.200.77) kamailiort+pengine (192.168.200.77) <->phone(192.168.18.45)

This is the machine C network enviroment:
[root@localhost kamailio]# ifconfig
eno16777736: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.10.200.77  netmask 255.255.0.0  broadcast 10.10.255.255
        inet6 fe80::250:56ff:fe2c:cb3e  prefixlen 64  scopeid 0x20<link>
        ether 00:50:56:2c:cb:3e  txqueuelen 1000  (Ethernet)
        RX packets 607566579  bytes 47583746201 (44.3 GiB)
        RX errors 0  dropped 35873  overruns 0  frame 0
        TX packets 689341706  bytes 960719135408 (894.7 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eno16777736:0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.200.77  netmask 255.255.0.0  broadcast 192.168.255.255
        ether 00:50:56:2c:cb:3e  txqueuelen 1000  (Ethernet)

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 3864802648  bytes 1107931184685 (1.0 TiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3864802648  bytes 1107931184685 (1.0 TiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

I have some doubts in the log：
     Nov 20 14:18:40 localhost rtpengine[79584]: INFO: 
     [ZGQ1MjUyN2I1MjUwYjg4MmIzNzA5NGM3NzgwNDNiMmQ.]: Replying to 'offer' from 
     127.0.0.1:52526 (elapsed time 0.000361 sec)
     Nov 20 14:18:40 localhost rtpengine[79584]: DEBUG: 
     [ZGQ1MjUyN2I1MjUwYjg4MmIzNzA5NGM3NzgwNDNiMmQ.]: Response dump for 'offer' to 
     127.0.0.1:52526: { "sdp": "v=0
     o=- 1 2 IN IP4 **192.168.200.77**
     s=CounterPath eyeBeam 1.5
     c=IN IP4 **192.168.200.77**
     t=0 0
     m=audio 30000 RTP/AVP 0 101
     a=alt:1 1 : 3Y74UWFG yxSDtS41 10.10.18.203 64892
     a=x-rtp-session-id:787601BB00C843D8A6F6112A5C649915
     a=rtpmap:0 PCMU/8000
     a=rtpmap:101 telephone-event/8000
     a=fmtp:101 0-15
     a=sendrecv
     a=rtcp:30001
     a=ice-ufrag:i0LqmZL9
     a=ice-pwd:P0xOuLqunJK9lQamsTcyoLHF3o
     a=candidate:YvBGmBmbAp3Rx2CA 1 UDP 2130706431 192.168.200 ...
     Nov 20 14:18:40 localhost rtpengine[79584]: DEBUG: 
     [ZGQ1MjUyN2I1MjUwYjg4MmIzNzA5NGM3NzgwNDNiMmQ.]: ... .77 30000 typ host
     a=candidate:YvBGmBmbAp3Rx2CA 2 UDP 2130706430 192.168.200.77 30001 typ host
     ", "result": "ok" }
     Nov 20 14:18:40 localhost /usr/local/sbin/kamailio[79674]: {1 1 INVITE 
     ZGQ1MjUyN2I1MjUwYjg4MmIzNzA5NGM3NzgwNDNiMmQ.} DEBUG: rtpengine [rtpengine.c:2252]: 
     rtpp_function_call(): proxy reply: d3:sdp541:v=0
     o=- 1 2 IN IP4 **192.168.200.77**
     s=CounterPath eyeBeam 1.5
     c=IN IP4 **192.168.200.77**
     t=0 0
     m=audio 30000 RTP/AVP 0 101
     a=alt:1 1 : 3Y74UWFG yxSDtS41 10.10.18.203 64892
     a=x-rtp-session-id:787601BB00C843D8A6F6112A5C649915
     a=rtpmap:0 PCMU/8000
     a=rtpmap:101 telephone-event/8000
     a=fmtp:101 0-15
     a=sendrecv
     a=rtcp:30001
     a=ice-ufrag:i0LqmZL9
     a=ice-pwd:P0xOuLqunJK9lQamsTcyoLHF3o
     a=candidate:YvBGmBmbAp3Rx2CA 1 UDP 2130706431 192.168.200.77 30000 typ host
     a=candidate:YvBGmBmbAp3Rx2CA 2 UDP 2130706430 192.168.200.77 30001 typ host
     6:result2:oke

As described in the log, the rtp stream is : 
phone(10.10.18.203)<-->(192.168.200.77) kamailiort+pengine (192.168.200.77) <-------------------------->phone(192.168.18.45)
I don't know if this is the reason that only one side has aduio.

I this the correct rtp steam is : 
phone(10.10.18.203)<-->(10.10..200.77) kamailiort+pengine (192.168.200.77) <-------------------------->phone(192.168.18.45)

This is the wireshark packet file in 10.10.18.203, the filter is "sip" : 
![2001 10 10 18 203](https://user-images.githubusercontent.com/30169891/48758356-bea04400-ecda-11e8-935f-9e6e8c51fffd.PNG)
This is the wireshark packet file in 192.168.18.45, the filter is "sip" : 
![1001 192 168 18 45](https://user-images.githubusercontent.com/30169891/48758375-d081e700-ecda-11e8-91c4-133d52613fb4.PNG)

I don't know how to properly modify the configuration file to make the RTP stream work properly.

**Comment by rfuchs** [comment]
Yeah the `answer` contains the wrong IP address. For some reason none of the extra options you have in your `rtpengine_manage` line show up in the log. Only `ICE=force` and `replace-origin` and `replace-session-connection` are there. It looks like an entirely different line in your config gets triggered?

**Comment by Sunldon** [comment]
Sorry for my mistake. In this test, ICE=force and replace-origin and replace-session-connection are the actual options.

In the another test , I use config as: "rtpengine_manage("codec-strip-all codec-transcode-PCMA codec-transcode-PCMU codec-transcode-G729 direction=priv direction=pub ICE=remove");" but it didn't work, The result is the same as the previous test. The reason for the failure is that the answer contains the wrong IP address(192.168.200.77).

**Comment by rfuchs** [comment]
Post the correct log then.

**Comment by Sunldon** [comment]
> Post the correct log then.

Now I am not in the work environment, I will give you a correct log tomorrow.

**Comment by Sunldon** [comment]
The startup patameters of rtpengine is : 
    
    ./rtpengine -n 127.0.0.1:7722 --interface=pub/10.10.200.77 --interface=priv/192.168.200.77 --log-level=7 --log-facility=local3
When I use rtpengine_manage as : 

        if(nat_uac_test("8")) {
                xinfo("11111111111111111111111111111111111111");
                rtpengine_manage("replace-origin replace-session-connection direction=priv direction=pub ICE=force");
        } else {
                xinfo("222222222222222222222222222222222222222");
                rtpengine_manage("codec-strip-all codec-transcode-PCMA codec-transcode-PCMU codec-transcode-G729 replace-origin replace-session-connection direction=priv direction=pub ICE=force ");
        }

The rtp stream behave as:
phone(10.10.18.203)<-->(10.10.200.77) kamailiort+pengine (10.10.200.77) <-------------------------->phone(192.168.18.45)

The first test's log is as below:
[kamai_rtpengine_v1.log](https://github.com/sipwise/rtpengine/files/2602222/kamai_rtpengine_v1.log)

When I change the options of  rtpengine_manage in config as : (I reverse the "direction" options )

        if(nat_uac_test("8")) {
                xinfo("11111111111111111111111111111111111111");
                rtpengine_manage("replace-origin replace-session-connection direction=pub direction=priv ICE=force");
        } else {
                xinfo("222222222222222222222222222222222222222");
                rtpengine_manage("codec-strip-all codec-transcode-PCMA codec-transcode-PCMU codec-transcode-G729 replace-origin replace-session-connection direction=pub direction=priv ICE=force ");
        }

The rtp stream behave as:
phone(10.10.18.203)<-->(192.168.200.77) kamailiort+pengine (192.168.200.77) <-------------------------->phone(192.168.18.45)

The second test's log is as below:
[kamai_rtpengine_v2.log](https://github.com/sipwise/rtpengine/files/2602223/kamai_rtpengine_v2.log)

There is my entire kamailio.cfg file:

[kamailio.zip](https://github.com/sipwise/rtpengine/files/2602238/kamailio.zip)

**Comment by rfuchs** [comment]
I believe you need to differentiate between offers and answers instead of using the `rtpengine_manage` magic to handle both. In the offer, you would use all transcoding options and the two `direction=` options, depending on where the offer is coming from and where it's going to. In the answer, you would omit all these options, as rtpengine already knows the codecs and the directions involved, and instructing it to do something else does not produce the desired results.

**Comment by Sunldon** [comment]
Thank you for your help. My problem has been solved.

**Comment by Ucheha** [comment]
@Sunldon can you please share your kamailio.cfg after fixing the issue, am still facing the issue.
or at least, if you can share the route[NATMANAGE] where the offer/answers being used.

**Comment by ecarruda** [comment]
> @Sunldon can you please share your kamailio.cfg after fixing the issue, am still facing the issue.
> or at least, if you can share the route[NATMANAGE] where the offer/answers being used.

Could you get this file?

**Comment by Sunldon** [comment]
> > @Sunldon can you please share your kamailio.cfg after fixing the issue, am still facing the issue.
> > or at least, if you can share the route[NATMANAGE] where the offer/answers being used.
> 
> Could you get this file?

I'm sorry I don't have this file anymore
