### ISSUE TITLE
capture id is not correctly set by the --homer-id parameter

### ISSUE THREAD

**Issue by lezozo** [sipwise/rtpengine#902]
here my command line:

rtpengine --interface=XXXXX --listen-ng=60000 --listen-cli=60001 --timeout=60 --silent-timeout=3600 --port-min=50000 --port-max=60000 --table=40 --log-level=2 --log-facility=local1 --homer-id=304 --homer=XXXXXXX:9060

but the capture ID that is sent to the homer server:  805371904

I run rtpengine in version 8.2.0.0

**Comment by rfuchs** [comment]
This has recently been fixed in c36a445

**Comment by lezozo** [comment]
I currently run a rtpengine binary compiled with this fix (8.2.0.0). Built from the latest source and dpkg-buildpackage.
But the problem remains.

**Comment by rfuchs** [comment]
Ah I guess it's missing the byte swap...

**Comment by rfuchs** [comment]
Commit b8a7973 (see above) should fix that.

**Comment by lezozo** [comment]
it does indeed!
Thanks a lot
